#include<stdio.h>
using namespace std;
int main()

{
   printf("............
          .................
          ..............
          ..............
          ....................")
    return 0;
}
